### ISSUE TITLE
'jumbotron-flud' should read 'jumbotron-fluid'

### ISSUE THREAD

**Issue by prpfr3** [PacktPublishing/Object-Oriented-PHP-and-MVC#2]
The bootstrap class 'jumbotron-flud' should read 'jumbotron-fluid' in all instances of apps > views > pages > index.php

**Comment by Sonakshis** [comment]
Hi,
Thank you for bringing this to our attention. We really appreciate your feedback. We have rectified the error. 
Happy learning!
